name: 'update by stargazed'
# This workflow runs at 00:30 everyday
on:
  schedule:
    -
      cron: '30 0 * * *'
jobs:
  build:
    name: 'stargazed update'
    runs-on: ubuntu-latest
    steps:
      -
        name: 'use gitHub actions'
        uses: actions/checkout@v2
      -
        name: 'use node.js 15.x'
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      -
        name: 'install package'
        run: 'npm install --global stargazed'
      -
        name: 'update repo'
        env:
          GITHUB_TOKEN: '${{ secrets.STARGAZED_TOKEN }}'
        run: 'stargazed --username "tg-z" --token ${GITHUB_TOKEN} --repo "stardom" --message "stargazed update by gitHub actions workflow" --sort'
